# Helm Chart for MCP Server Phase 6-3
# Production-ready Helm chart

apiVersion: v2
name: mcp-server
description: A Helm chart for MCP Server Phase 6-3 Production Deployment
type: application
version: 1.0.0
appVersion: "phase6-3"

keywords:
  - mcp
  - drone
  - control
  - api
  - server
  - nlp
  - ai

home: https://github.com/coolerking/mfg_drone_by_claudecode
sources:
  - https://github.com/coolerking/mfg_drone_by_claudecode

maintainers:
  - name: MCP Server Team
    email: support@mcpserver.com

dependencies:
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "15.5.3"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled

annotations:
  category: Application
  licenses: MIT