# Secrets for MCP Server Phase 6-3
# Sensitive configuration data

apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: mcp-server
  labels:
    app: mcp-server
    environment: production
    version: phase6-3
type: Opaque
data:
  # JWT Secret (base64 encoded)
  # Generate with: openssl rand -base64 32
  JWT_SECRET: "Y2hhbmdlLW1lLXRvLWEtc3Ryb25nLXNlY3VyZS1qd3Qtc2VjcmV0LWZvci1wcm9kdWN0aW9uLWRlcGxveW1lbnQ="
  
  # Admin User Credentials
  ADMIN_USERNAME: "YWRtaW4="  # admin
  ADMIN_PASSWORD: "YWRtaW4xMjM0NTY3ODkw"  # admin1234567890
  
  # Operator User Credentials
  OPERATOR_USERNAME: "b3BlcmF0b3I="  # operator
  OPERATOR_PASSWORD: "b3BlcmF0b3IxMjM0NTY3ODkw"  # operator1234567890
  
  # ReadOnly User Credentials
  READONLY_USERNAME: "cmVhZG9ubHk="  # readonly
  READONLY_PASSWORD: "cmVhZG9ubHkxMjM0NTY3ODkw"  # readonly1234567890
  
  # Redis Password
  REDIS_PASSWORD: "cmVkaXNwYXNzd29yZDEyMzQ1Njc4OTA="  # redispassword1234567890
  
  # Backend API Key
  BACKEND_API_KEY: "YmFja2VuZC1hcGkta2V5LWZvci1wcm9kdWN0aW9uLWRlcGxveW1lbnQ="
  
  # Database Credentials (if needed)
  DB_HOST: "ZGF0YWJhc2Utc2VydmljZQ=="  # database-service
  DB_PORT: "NTQzMg=="  # 5432
  DB_NAME: "bWNwX3NlcnZlcl9kYg=="  # mcp_server_db
  DB_USERNAME: "bWNwX3VzZXI="  # mcp_user
  DB_PASSWORD: "bWNwX3Bhc3N3b3JkMTIzNDU2Nzg5MA=="  # mcp_password1234567890

---
# TLS Secret for SSL certificates
apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-tls
  namespace: mcp-server
  labels:
    app: mcp-server
    environment: production
type: kubernetes.io/tls
data:
  # Generate with:
  # openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
  # kubectl create secret tls mcp-server-tls --cert=cert.pem --key=key.pem
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

---
# Grafana Admin Secret
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: mcp-server
  labels:
    app: grafana
    environment: production
type: Opaque
data:
  # Grafana admin credentials
  GRAFANA_USER: "YWRtaW4="  # admin
  GRAFANA_PASSWORD: "Z3JhZmFuYWFkbWluMTIzNDU2Nzg5MA=="  # grafanaadmin1234567890